"""Create a flat BI-ready export for Power BI or dashboard prototyping."""

import pandas as pd

from config import REPORT_FILES, ensure_directories


def build_powerbi_export() -> pd.DataFrame:
    customer = pd.read_csv(REPORT_FILES["customer_table"])
    monthly = pd.read_csv(REPORT_FILES["monthly_summary"])
    latest_month = monthly.sort_values("reporting_month").iloc[-1]

    export = customer.copy()
    for column in [
        "reporting_month",
        "total_revenue",
        "collection_rate",
        "overdue_rate",
        "target_revenue",
        "target_achievement_rate",
        "mom_revenue_change",
    ]:
        export[column] = latest_month[column]

    export["risk_category"] = export["risk_rating"].map({"Low": "Low Risk", "Medium": "Medium Risk", "High": "High Risk"})
    export["overdue_category"] = pd.cut(
        export["overdue_ratio"],
        bins=[-0.01, 0.0, 0.1, 0.3, 1.0],
        labels=["No Overdue", "Low Overdue", "Watchlist", "High Overdue"],
    ).astype(str)
    export["collection_status"] = export["outstanding_amount"].apply(lambda value: "Outstanding" if value > 0 else "Collected")
    export["dashboard_refresh_note"] = "Synthetic portfolio export generated by automated reporting workflow"

    columns = [
        "reporting_month",
        "customer_id",
        "customer_name",
        "country",
        "industry",
        "company_size",
        "account_manager",
        "risk_rating",
        "risk_category",
        "total_invoice_amount",
        "collected_amount",
        "outstanding_amount",
        "overdue_amount",
        "overdue_ratio",
        "overdue_category",
        "collection_status",
        "avg_days_to_payment",
        "contract_value",
        "active_contracts",
        "open_cases",
        "reporting_status",
        "exception_flag",
        "total_revenue",
        "collection_rate",
        "overdue_rate",
        "target_revenue",
        "target_achievement_rate",
        "mom_revenue_change",
        "dashboard_refresh_note",
    ]
    return export[columns].sort_values("outstanding_amount", ascending=False)


def main() -> None:
    ensure_directories()
    export = build_powerbi_export()
    export.to_csv(REPORT_FILES["powerbi_export"], index=False)
    print(f"Power BI-ready export written to {REPORT_FILES['powerbi_export']} ({len(export):,} rows)")


if __name__ == "__main__":
    main()
